[tool.isort]
line_length = 79
force_single_line = true

[tool.black]
line-length = 79
preview = true

[tool.pyright]
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnknownVariableType = false
exclude = ["**/venv", "**/migrations"]